Add time shift detection
admin-ch/CovidCertificate-SDK-iOS pull request #99
Opened 2021-11-05 10:49 UTC by ubfelix

With this change, the SDK detects during every check (trust list, revocation list, national rules) whether the device time significantly differs from the server time and if so, returns a new `TIME_INCONSISTENCY` error. The "Date" and "Age" headers from the HTTP response are used to determine the server time.

2021-11-05 20:12 UTC, UBaggeler commented on Sources/CovidCertificateSDK/TrustList/TrustListManager.swift
> -            if error == nil {
Setting `self.lastError` should still be done on the `operationQueue`, to make sure this variable is synchronized and only read/written from this queue.

2021-11-05 20:22 UTC, UBaggeler commented on Sources/CovidCertificateSDK/TrustList/TrustListManager.swift
> +    private static let allowedServerTimeDiff: TimeInterval = 60 * 10 // 10 minutes
Let's set it to 2h for now and then expose it as a configurable parameter, which the users of the SDK can overwrite.

2021-11-05 20:23 UTC, UBaggeler requested changes
I did a first pass and left a couple of comments. Looks good overall.

2021-11-08 13:25 UTC, stmitt approved these changes

2021-11-08 14:22 UTC, UBaggeler approved these changes

2021-11-08 14:22 UTC, merged